### ISSUE TITLE
Vote on cards

### ISSUE THREAD

**Issue by badabam** [badabam/lean-coffee-board#8]
## Value statement
**As**  a group of users
**I want to** vote on cards
**in order to** decide what topic to talk about

## Description
![vote-on-cards](https://user-images.githubusercontent.com/157286/110300818-a8c40380-7ff7-11eb-9b52-2777a3b4a7a2.png)

## Acceptance criteria
- [x] Starts with 0 votes and shows a plus sign
- [x] Votes count up on each click (plus sign turns into number)
- [x] Limit is 99 votes per card
- [x] You can not undo a vote 
- [x] Votes persist in backend
- [x] Cards are sorted by number of votes descending

## Todos
- [x] Create branch
- [x] Create Card component (in single file) = in storybook
- [x] Write component tests
- [x] Add new propTypes
- [x] Implement voting logic
- [x] Add missing styles
